// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    BaseButton: typeof import("./src/components/BaseButton.vue")["default"];
    BaseDropdown: typeof import("./src/components/BaseDropdown.vue")["default"];
    BaseLink: typeof import("./src/components/BaseLink.vue")["default"];
    BaseModal: typeof import("./src/components/BaseModal.vue")["default"];
    ButtonIcon: typeof import("./src/components/ButtonIcon.vue")["default"];
    ButtonLarge: typeof import("./src/components/ButtonLarge.vue")["default"];
    ButtonWallet: typeof import("./src/components/ButtonWallet.vue")["default"];
    ContainerMain: typeof import("./src/components/ContainerMain.vue")["default"];
    DropdownAccount: typeof import("./src/components/DropdownAccount.vue")["default"];
    HomeConnect: typeof import("./src/components/HomeConnect.vue")["default"];
    ModalConnect: typeof import("./src/components/ModalConnect.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SidebarAccount: typeof import("./src/components/SidebarAccount.vue")["default"];
    TheNavbar: typeof import("./src/components/TheNavbar.vue")["default"];
    TheSecondaryColumn: typeof import("./src/components/TheSecondaryColumn.vue")["default"];
    TheSidebar: typeof import("./src/components/TheSidebar.vue")["default"];
    TheSidebarResponsive: typeof import("./src/components/TheSidebarResponsive.vue")["default"];
  }
}

export {};
